### ISSUE TITLE
wrong State departments for Vendredi Saint & Saint Etienne

### ISSUE THREAD

**Issue by nouknouk** [lunarok/jeedom_dayinfo#12]
https://github.com/lunarok/jeedom_dayinfo/blob/c65c4973e7083846b362c389cb8dd1ef2f674cec/core/class/dayinfo.class.php#L126

cf. Wikipedia: https://fr.wikipedia.org/wiki/F%C3%AAtes_et_jours_f%C3%A9ri%C3%A9s_en_France#Tableau_r.C3.A9capitulatif

btw, thanks for this amazing plugin :)

**Comment by lunarok** [comment]
https://github.com/lunarok/jeedom_dayinfo/commit/821442d0d8f886ce0f7b2116f9ac2a92e1930db4
