### ISSUE TITLE
Information 'numero du jour'

### ISSUE THREAD

**Issue by ADefossez-Zenika** [lunarok/jeedom_dayinfo#16]
Bonjour, 
Bravo pour ton plugin, j'ai juste besoin d'une information en plus, pour ordonnancer mes scenarios : le numero du jour dans l'année. (de 0 a 365/366).

Je m'occupe du développement et t'envoie la PR, j'ai juste besoin de quelques jours ;) 
Ca devrait être bon d'ici la fin du mois.

**Comment by lunarok** [comment]
ok, je vais surement revoir une partie du code aussi pour rajouter différentes cmds infos

**Comment by lunarok** [comment]
C'est fait, et la doc aussi

**Comment by ADefossez-Zenika** [comment]
ah, bah nikel ;) J'avais préparé mon environnement, et allais profiter de mon vendredi pour le faire, mais si c'est fait, parfait :)
