### ISSUE TITLE
Mise à jour des fichiers ICS

### ISSUE THREAD

**Issue by FabriceGo** [lunarok/jeedom_dayinfo#22]
Bonjour Lunarok,

Actuellement, les calendriers ICS ne sont pas à jour, ils indiquent une fin de congés d'été dans 365 jours (depuis au moins 1 mois). Je viens de télécharger le fichier ICS de la zone C pour voir. Et celui-ci indique bien une fin de vacances dans 121 jours pour ce qui concerne la zone C.
Je n'arrive pas à le faire sur ton Github.
Merci.

**Comment by lunarok** [comment]
Fait : https://github.com/lunarok/jeedom_dayinfo/commit/634b21932c0dd0bf4c33d918178615e3ab14b0f0

**Comment by FabriceGo** [comment]
Merci beaucoup !
