### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by MickaelRoy** [lunarok/jeedom_dayinfo#32]
Hello Lunarok, 

Tout d'abord merci pour tes nombreuses contributions, J'ai deux idées pour faire évoluer ce plugin, je te laisse juger et traiter si ca te convient.
Avoir une commande info, qui précise quelle est l'occurrence du jour en cours. ex:
nous sommes le dim 09/01/22 soit 2
si nous sommes le 16 alors 3 devrait être retourné.
et ainsi de suite. 

Avoir une commande info qui retourne si l'occurrence du jour en cours est la dernière. ex:
nous sommes le vendredi 28/01/22. alors il retourne 1 (comme un booleen)
Si nous somme le samedi 22, alors 0.

Ceci aiderait la gestion des poubelles dans les scenarii.
A l'heure actuelle je traite ca avec un bout de script python. mais la commu sera peut être intéressée.

Bonne continuation !

**Comment by lunarok** [comment]
Mis en place ici : https://github.com/lunarok/jeedom_dayinfo/commit/66ee96740309a6ace58fa95c21b80a06d633cd8e
