### ISSUE TITLE
Nom des saisons en français

### ISSUE THREAD

**Issue by Gis70** [lunarok/jeedom_dayinfo#6]
Bonjour, 

Serais t'il possible d'avoir les noms des saisons en français : 

Dans /core/php/***season

```
 public function getSeason($hemisphere = "nothern") {
          if ($hemisphere == "nothern")
             $season_names = array('Spring', 'Summer', 'Fall', 'Winter');
          else
             $season_names = array('Fall', 'Winter', 'Spring', 'Summer');
          return $season_names[$this->getPhase() - 1];
       }
       public function getNextSeason($hemisphere = "nothern") {
          if ($hemisphere == "nothern")
             $season_names = array('', 'Summer', 'Fall', 'Winter', 'Spring');
          else
             $season_names = array('', 'Winter', 'Spring', 'Summer', 'Fall');
          return $season_names[$this->getPhase()];
       }
```

J'ai testé en local sur mon jeedom en simplement remplaçant l'anglais par du français ça fonctionne, mais je ne suis pas certain que ça fonctionnera toujours au changement réel de saison. Donc je n'ai pas fait de PR. Mais si tu penses que c'est OK comme ça alors let's go.

Merci.

**Comment by lunarok** [comment]
Non, je souhaite pas mettre de VF car c'est gênant pour les non francophone. Je sais plus si la liste est dans la d'oc mais ça serait la solution multilingue

**Comment by Gis70** [comment]
Et tu n'aurais pas moyen de le faire @lunarok, je viens d'essayer de rajouter les mots traduits dans le fr.json mais ça ne marche pas, il doit manquer autre chose. sinon si tu sais m'aiguiller pour que je m'en charge... Merci

**Comment by lunarok** [comment]
Non les json sont pour l'interface ils ne traduisent pas le resultats des cmds. Il ne peut y avoir qu'un mot sinon ca devient le bordel pour les autres langues car impact dans les docs etc. Au pire c'est rajouter dans la doc les mots donnés pour les saisons (la lune c'est pareil)

**Comment by MADomotique** [comment]
> Non, je souhaite pas mettre de VF car c'est gênant pour les non francophone. 

Hello, 
En quoi le fait d'avoir les noms des saisons en français serait plus génant pour les non francophones que le fait d'avoir les saisons en anglais pour les francophones ? 
Quelle la proportion de users non francophones par rapport aux utilisateurs francophones de ce plugin ?  

A priori, une piste de solution est proposée pour la traduction des saisons 
https://github.com/lunarok/jeedom_dayinfo/blob/cd8cea7b48d12f15bc766aa8220d6e0fc0540879/core/php/class.Season.php#L22-L23

**Comment by MADomotique** [comment]
Autre sujet : comment est déterminé l'hémisphère dans le plugin DayInfo ? 
https://github.com/lunarok/jeedom_dayinfo/blob/cd8cea7b48d12f15bc766aa8220d6e0fc0540879/core/php/class.Season.php#L24-L26

https://github.com/lunarok/jeedom_dayinfo/blob/cd8cea7b48d12f15bc766aa8220d6e0fc0540879/core/php/class.Season.php#L136-L150
Visiblement l'hémisphère Nord est utilisé par défaut et je n'ai pas trouvé dans le code de calcul pour déterminer l'hémisphère Nord/Sud. Donc à priori, le plugin DayInfo ne sera d'aucune utilité pour nos compatriotes de La Réunion.  
J'imagine mal un non francophones de l'hémisphère sud venir faire une réclamation ici.
