### ISSUE TITLE
week end toujours à faux

### ISSUE THREAD

**Issue by kornflex** [lunarok/jeedom_dayinfo#8]
Bonjour,
Depuis la dernière update, mon week end est toujours à 0.

Dans la documentation, j'ai vu qu'il fallait utiliser le plugin GeoLoc. Je l'ai donc installé, mais toujours pareil :/

dois je aussi installé "Trajet" ? 

Merci beaucoup

**Comment by lunarok** [comment]
Le support c'est sur le forum, les issues se sont pour les bugs pas pour les questions d'utilisation
On utilise pas le plugin Geoloc avec ce plugin, et infos diverses il suffit de regarder il ne demande pas de localisation
